# -*- coding: utf-8 -*-
"""Deliverable8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ezO0zArKpYGUYVtQ2PQ-omefYZHdsm8
"""

import numpy as np

def Method1():
  x = 0
  while (True):
    x = input("Please enter an integer number between 5 and 15: ")
    try:
      x = int(x)
    except:
      x = 0
    if(5<x<15):
      list1 = np.random.randint(10,50, size = x)
      print("The numbers in the list are: ", list1)
      break
  return list1

def Method2():
  list1 = Method1()
  sum1 = sum(list1)
  print("The sume of the elements in the list is: ", sum1)

Method2()